CREATE DATABASE react_blog_app;

CREATE TABLE IF NOT EXISTS posts(id VARCHAR(255) NOT NULL PRIMARY KEY, title VARCHAR(250) NOT NULL, body VARCHAR(55000) NOT NULL, post_date DATE NOT NULL);

CREATE TABLE IF NOT EXISTS comments(id VARCHAR(255) NOT NULL PRIMARY KEY, author VARCHAR(255) NOT NULL, body VARCHAR(55000) NOT NULL, comment_date TIMESTAMP WITH TIME ZONE NOT NULL, post_id VARCHAR(255) NOT NULL REFERENCES posts(id), parent VARCHAR(255));